#pragma once

#define OPERATOR int
#define OPERATOR_NONE 0
#define OPERATOR_PLUS 1
#define OPERATOR_MINUS 2
#define OPERATOR_MULTIPLY 3
#define OPERATOR_DIVIDE 4
#define OPERATOR_REMAINDER 5
#define OPERATOR_PLUSONE 6
#define OPERATOR_MINUSONE 7
#define OPERATOR_CONCAT 8
#define OPERATOR_GREATER_THAN 9
#define OPERATOR_GREATER_THAN_OR_EQUAL_TO 10
#define OPERATOR_LESS_THAN 11
#define OPERATOR_LESS_THAN_OR_EQUAL_TO 12
#define OPERATOR_EQUAL_TO 13
#define OPERATOR_NOT_EQUAL_TO 14
#define OPERATOR_AND 15
#define OPERATOR_NOT 16/*
#define OPERATOR_PLUS = 17;
#define OPERATOR_PLUS = 18;
#define OPERATOR_PLUS = 19;
#define OPERATOR_PLUS = 20;
#define OPERATOR_PLUS = 1;
#define OPERATOR_PLUS = 1;
#define OPERATOR_PLUS = 1;*/
